### ISSUE TITLE
Demo: Fetch inappropriate display

### ISSUE THREAD

**Issue by gsamad0** [gsamad0/pluralsight-js-dev-env#5] opened 2019-06-22 09:52 UTC
Under module 11, chapter 4 (Demo:fetch)

My final display looks like this, 

Users
 | Id | First Name | Last Name | Email

-------------------------------------------------------------------------------------

While yours looks like this:

Users
           | Id | First Name | Last Name | Email
Delete 1    Bob               Smith           bob@gmail.com
Delete 2    Tammy          Norton         tnorton@yahoo.com
Delete 3    Tina               Lee               lee.tina@hotmail.com
------------------------------------------------------------------------------------

i did crosscheck my codes thoroughly but still couldn't find out where i got it wrong.

 Please help.

My current work is the sixth commit.

**Comment by coryhouse** [comment] 2019-06-22 11:23
I'll give you a hint: Open the dev tools and note the error:

`Uncaught (in promise) TypeError: Cannot set property 'innerHTML' of null at index.js:19`

**Comment by coryhouse** [comment] 2019-06-22 11:24
If that hint doesn't help, I'll tell you the answer. But I bet you can figure it out now.

**Comment by gsamad0** [comment] 2019-06-22 12:56
i was able to detect it but couldnt fix it.

global.document.getElementById('users').innerHTML = usersBody;
});

**Comment by coryhouse** [comment] 2019-06-22 13:10
In index.html, the declaration for the tbody is incorrect. It has a leading slash. Self closing tags should have a trailing slash. :)

**Closed by coryhouse** 2019-06-22 13:10 UTC

**Comment by gsamad0** [comment] 2019-06-22 13:34
its has been corrected, yet it is still the same.

crosscheck it in my seventh commit.

Thanks for your patient and assistance with me.

**Comment by coryhouse** [comment] 2019-06-22 17:24
Your casing on this selector is incorrect: 

`global.document.getElementById('Users').innerHTML = usersBody;`

**Comment by gsamad0** [comment] 2019-06-22 19:53
Its looks exactly how you wrote it base on what i saw. Please enlighten me, as you much have observed so far that i am still at beginner stage. Thanks

**Comment by coryhouse** [comment] 2019-06-22 21:02
Selectors are case sensitive, so you need to use a lowercase u on users.

`global.document.getElementById('users').innerHTML = usersBody;`

(Note that the id is lowercase in index.html)

**Comment by gsamad0** [comment] 2019-06-22 23:09
I have commit my current status "ninth commit" for you see that i did corrected the case error i made yet the situation is still the same.
Below is the detailed error it showed in the VS terminal.

$ npm start -s
Starting app in dev mode...

:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\src\api\userApi.js (3/0)
  ✖   2:8   'getBaseUrl' is defined but never used  no-unused-vars
  ✖   4:17  'getBaselUrl' is not defined            no-undef
  ✖  10:29  'id' is defined but never used          no-unused-vars

C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\src\index.js (1/0)
  ✖  3:19  deleteUser not found in './api/userApi'  import/named

✖ 4 errors (11:51:32 PM)

  \{^_^}/ hi!

  Loading src/api/db.json
  Done

  Resources
  http://localhost:3001/users

  Home
  http://localhost:3001

  Type s + enter at any time to create a snapshot of the database
  Watching...

**Comment by coryhouse** [comment] 2019-06-23 00:36
Open the devtools in the browser and you can see the error: getBaselUrl is not defined in userApi.js on line 4.

There's a typo on that line.

**Comment by gsamad0** [comment] 2019-06-23 08:20
Thank you. Corrected, it is showing now.
but it is remain this below error showing in the VS terminal. as a result, when i click on delete it isn't working. i guess this is where the error is emanating as a result of utilizing the developer tool, i just don't know how to rectify it.

VS terminal indicating error:  C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\src\index.js (1/0)
  ✖  3:19  deleteUser not found in './api/userApi'  import/named

✖ 1 error (8:41:14 AM)

dev tool error indicating:  **" Uncaught TypeError: (0 , _userApi.deleteUser) is not a functionat HTMLAnchorElement.link.onclick (index.js:29)" = deleteUser(element.attributes["data-id"].value);** 

My current status has been push to the tenth commit.

Thank you very much. really appreciate the guidance.

**Comment by gsamad0** [comment] 2019-06-23 08:27
Thank you. Corrected, it is showing now.
but it is remain this below error showing in the VS terminal. as a result, when i click on delete it isn't working.

VS terminal indicating error: C:\Users\Abdul Samad\Desktop\pluralsight-js-dev-env\src\index.js (1/0)
✖ 3:19 deleteUser not found in './api/userApi' import/named

✖ 1 error (8:41:14 AM)

dev tool error indicating: " Uncaught TypeError: (0 , _userApi.deleteUser) is not a functionat HTMLAnchorElement.link.onclick (index.js:29)" 
which is on line 29 of index.js  "deleteUser(element.attributes["data-id"].value);"

My current status has been push to the tenth commit.

Thank you very much. really appreciate the guidance.

**Comment by coryhouse** [comment] 2019-06-23 11:33
It's telling you what the error is: userApi.deleteUser is not a function. 

I'm happy to help, but for you to learn it's important to read the error, then think about what it means. This error clearly states what the problem is: There's is no function named deleteUser in userApi.js.

When stuck, compare your code to my code (download from the course exercise files)

**Comment by gsamad0** [comment] 2019-06-23 15:10
Thank you for being patient with me. 
Eventually figured it out.
It was a typo error as well.

Glad you implore me to resolved it myself, and i am proud i did., Although i know you gave me a hit, :) 💯 

wish you a beautiful and blissful weekend.
